// Generated by gencpp from file robots_moviles_package/msg1_pose.msg
// DO NOT EDIT!


#ifndef ROBOTS_MOVILES_PACKAGE_MESSAGE_MSG1_POSE_H
#define ROBOTS_MOVILES_PACKAGE_MESSAGE_MSG1_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robots_moviles_package
{
template <class ContainerAllocator>
struct msg1_pose_
{
  typedef msg1_pose_<ContainerAllocator> Type;

  msg1_pose_()
    : position(0)
    , angle(0.0)  {
    }
  msg1_pose_(const ContainerAllocator& _alloc)
    : position(0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _position_type;
  _position_type position;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::robots_moviles_package::msg1_pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robots_moviles_package::msg1_pose_<ContainerAllocator> const> ConstPtr;

}; // struct msg1_pose_

typedef ::robots_moviles_package::msg1_pose_<std::allocator<void> > msg1_pose;

typedef boost::shared_ptr< ::robots_moviles_package::msg1_pose > msg1_posePtr;
typedef boost::shared_ptr< ::robots_moviles_package::msg1_pose const> msg1_poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robots_moviles_package::msg1_pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robots_moviles_package::msg1_pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robots_moviles_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'robots_moviles_package': ['/home/sergio/catkin_ws/src/robots_moviles_package/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robots_moviles_package::msg1_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robots_moviles_package::msg1_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robots_moviles_package::msg1_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robots_moviles_package::msg1_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robots_moviles_package::msg1_pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robots_moviles_package::msg1_pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robots_moviles_package::msg1_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "968abc20dbb963a7de947b6bafc3c12b";
  }

  static const char* value(const ::robots_moviles_package::msg1_pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x968abc20dbb963a7ULL;
  static const uint64_t static_value2 = 0xde947b6bafc3c12bULL;
};

template<class ContainerAllocator>
struct DataType< ::robots_moviles_package::msg1_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robots_moviles_package/msg1_pose";
  }

  static const char* value(const ::robots_moviles_package::msg1_pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robots_moviles_package::msg1_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 position\n\
float64 angle\n\
";
  }

  static const char* value(const ::robots_moviles_package::msg1_pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robots_moviles_package::msg1_pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg1_pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robots_moviles_package::msg1_pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robots_moviles_package::msg1_pose_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTS_MOVILES_PACKAGE_MESSAGE_MSG1_POSE_H
