// Generated by gencpp from file robots_moviles_package/posicion.msg
// DO NOT EDIT!


#ifndef ROBOTS_MOVILES_PACKAGE_MESSAGE_POSICION_H
#define ROBOTS_MOVILES_PACKAGE_MESSAGE_POSICION_H

#include <ros/service_traits.h>


#include <robots_moviles_package/posicionRequest.h>
#include <robots_moviles_package/posicionResponse.h>


namespace robots_moviles_package
{

struct posicion
{

typedef posicionRequest Request;
typedef posicionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct posicion
} // namespace robots_moviles_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robots_moviles_package::posicion > {
  static const char* value()
  {
    return "049d75b744ba6418566a32f18f43c69c";
  }

  static const char* value(const ::robots_moviles_package::posicion&) { return value(); }
};

template<>
struct DataType< ::robots_moviles_package::posicion > {
  static const char* value()
  {
    return "robots_moviles_package/posicion";
  }

  static const char* value(const ::robots_moviles_package::posicion&) { return value(); }
};


// service_traits::MD5Sum< ::robots_moviles_package::posicionRequest> should match 
// service_traits::MD5Sum< ::robots_moviles_package::posicion > 
template<>
struct MD5Sum< ::robots_moviles_package::posicionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robots_moviles_package::posicion >::value();
  }
  static const char* value(const ::robots_moviles_package::posicionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robots_moviles_package::posicionRequest> should match 
// service_traits::DataType< ::robots_moviles_package::posicion > 
template<>
struct DataType< ::robots_moviles_package::posicionRequest>
{
  static const char* value()
  {
    return DataType< ::robots_moviles_package::posicion >::value();
  }
  static const char* value(const ::robots_moviles_package::posicionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robots_moviles_package::posicionResponse> should match 
// service_traits::MD5Sum< ::robots_moviles_package::posicion > 
template<>
struct MD5Sum< ::robots_moviles_package::posicionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robots_moviles_package::posicion >::value();
  }
  static const char* value(const ::robots_moviles_package::posicionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robots_moviles_package::posicionResponse> should match 
// service_traits::DataType< ::robots_moviles_package::posicion > 
template<>
struct DataType< ::robots_moviles_package::posicionResponse>
{
  static const char* value()
  {
    return DataType< ::robots_moviles_package::posicion >::value();
  }
  static const char* value(const ::robots_moviles_package::posicionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTS_MOVILES_PACKAGE_MESSAGE_POSICION_H
