// Generated by gencpp from file robots_moviles_package/posicionRequest.msg
// DO NOT EDIT!


#ifndef ROBOTS_MOVILES_PACKAGE_MESSAGE_POSICIONREQUEST_H
#define ROBOTS_MOVILES_PACKAGE_MESSAGE_POSICIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robots_moviles_package
{
template <class ContainerAllocator>
struct posicionRequest_
{
  typedef posicionRequest_<ContainerAllocator> Type;

  posicionRequest_()
    : direccion(0)  {
    }
  posicionRequest_(const ContainerAllocator& _alloc)
    : direccion(0)  {
  (void)_alloc;
    }



   typedef uint8_t _direccion_type;
  _direccion_type direccion;





  typedef boost::shared_ptr< ::robots_moviles_package::posicionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robots_moviles_package::posicionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct posicionRequest_

typedef ::robots_moviles_package::posicionRequest_<std::allocator<void> > posicionRequest;

typedef boost::shared_ptr< ::robots_moviles_package::posicionRequest > posicionRequestPtr;
typedef boost::shared_ptr< ::robots_moviles_package::posicionRequest const> posicionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robots_moviles_package::posicionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robots_moviles_package::posicionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robots_moviles_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robots_moviles_package::posicionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robots_moviles_package::posicionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robots_moviles_package::posicionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robots_moviles_package::posicionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robots_moviles_package::posicionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robots_moviles_package::posicionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robots_moviles_package::posicionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5bf7493d22156dd1f31812556249ef8";
  }

  static const char* value(const ::robots_moviles_package::posicionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5bf7493d22156ddULL;
  static const uint64_t static_value2 = 0x1f31812556249ef8ULL;
};

template<class ContainerAllocator>
struct DataType< ::robots_moviles_package::posicionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robots_moviles_package/posicionRequest";
  }

  static const char* value(const ::robots_moviles_package::posicionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robots_moviles_package::posicionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 direccion\n\
";
  }

  static const char* value(const ::robots_moviles_package::posicionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robots_moviles_package::posicionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direccion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct posicionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robots_moviles_package::posicionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robots_moviles_package::posicionRequest_<ContainerAllocator>& v)
  {
    s << indent << "direccion: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.direccion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTS_MOVILES_PACKAGE_MESSAGE_POSICIONREQUEST_H
