// Generated by gencpp from file robots_moviles_package/serv1_posicion.msg
// DO NOT EDIT!


#ifndef ROBOTS_MOVILES_PACKAGE_MESSAGE_SERV1_POSICION_H
#define ROBOTS_MOVILES_PACKAGE_MESSAGE_SERV1_POSICION_H

#include <ros/service_traits.h>


#include <robots_moviles_package/serv1_posicionRequest.h>
#include <robots_moviles_package/serv1_posicionResponse.h>


namespace robots_moviles_package
{

struct serv1_posicion
{

typedef serv1_posicionRequest Request;
typedef serv1_posicionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct serv1_posicion
} // namespace robots_moviles_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robots_moviles_package::serv1_posicion > {
  static const char* value()
  {
    return "049d75b744ba6418566a32f18f43c69c";
  }

  static const char* value(const ::robots_moviles_package::serv1_posicion&) { return value(); }
};

template<>
struct DataType< ::robots_moviles_package::serv1_posicion > {
  static const char* value()
  {
    return "robots_moviles_package/serv1_posicion";
  }

  static const char* value(const ::robots_moviles_package::serv1_posicion&) { return value(); }
};


// service_traits::MD5Sum< ::robots_moviles_package::serv1_posicionRequest> should match 
// service_traits::MD5Sum< ::robots_moviles_package::serv1_posicion > 
template<>
struct MD5Sum< ::robots_moviles_package::serv1_posicionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robots_moviles_package::serv1_posicion >::value();
  }
  static const char* value(const ::robots_moviles_package::serv1_posicionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robots_moviles_package::serv1_posicionRequest> should match 
// service_traits::DataType< ::robots_moviles_package::serv1_posicion > 
template<>
struct DataType< ::robots_moviles_package::serv1_posicionRequest>
{
  static const char* value()
  {
    return DataType< ::robots_moviles_package::serv1_posicion >::value();
  }
  static const char* value(const ::robots_moviles_package::serv1_posicionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robots_moviles_package::serv1_posicionResponse> should match 
// service_traits::MD5Sum< ::robots_moviles_package::serv1_posicion > 
template<>
struct MD5Sum< ::robots_moviles_package::serv1_posicionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robots_moviles_package::serv1_posicion >::value();
  }
  static const char* value(const ::robots_moviles_package::serv1_posicionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robots_moviles_package::serv1_posicionResponse> should match 
// service_traits::DataType< ::robots_moviles_package::serv1_posicion > 
template<>
struct DataType< ::robots_moviles_package::serv1_posicionResponse>
{
  static const char* value()
  {
    return DataType< ::robots_moviles_package::serv1_posicion >::value();
  }
  static const char* value(const ::robots_moviles_package::serv1_posicionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTS_MOVILES_PACKAGE_MESSAGE_SERV1_POSICION_H
