// Generated by gencpp from file sesionesPlanning/apunto.msg
// DO NOT EDIT!


#ifndef SESIONESPLANNING_MESSAGE_APUNTO_H
#define SESIONESPLANNING_MESSAGE_APUNTO_H

#include <ros/service_traits.h>


#include <sesionesPlanning/apuntoRequest.h>
#include <sesionesPlanning/apuntoResponse.h>


namespace sesionesPlanning
{

struct apunto
{

typedef apuntoRequest Request;
typedef apuntoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct apunto
} // namespace sesionesPlanning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sesionesPlanning::apunto > {
  static const char* value()
  {
    return "049d75b744ba6418566a32f18f43c69c";
  }

  static const char* value(const ::sesionesPlanning::apunto&) { return value(); }
};

template<>
struct DataType< ::sesionesPlanning::apunto > {
  static const char* value()
  {
    return "sesionesPlanning/apunto";
  }

  static const char* value(const ::sesionesPlanning::apunto&) { return value(); }
};


// service_traits::MD5Sum< ::sesionesPlanning::apuntoRequest> should match 
// service_traits::MD5Sum< ::sesionesPlanning::apunto > 
template<>
struct MD5Sum< ::sesionesPlanning::apuntoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sesionesPlanning::apunto >::value();
  }
  static const char* value(const ::sesionesPlanning::apuntoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sesionesPlanning::apuntoRequest> should match 
// service_traits::DataType< ::sesionesPlanning::apunto > 
template<>
struct DataType< ::sesionesPlanning::apuntoRequest>
{
  static const char* value()
  {
    return DataType< ::sesionesPlanning::apunto >::value();
  }
  static const char* value(const ::sesionesPlanning::apuntoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sesionesPlanning::apuntoResponse> should match 
// service_traits::MD5Sum< ::sesionesPlanning::apunto > 
template<>
struct MD5Sum< ::sesionesPlanning::apuntoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sesionesPlanning::apunto >::value();
  }
  static const char* value(const ::sesionesPlanning::apuntoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sesionesPlanning::apuntoResponse> should match 
// service_traits::DataType< ::sesionesPlanning::apunto > 
template<>
struct DataType< ::sesionesPlanning::apuntoResponse>
{
  static const char* value()
  {
    return DataType< ::sesionesPlanning::apunto >::value();
  }
  static const char* value(const ::sesionesPlanning::apuntoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SESIONESPLANNING_MESSAGE_APUNTO_H
