// Generated by gencpp from file sesionesPlanning/apuntoRequest.msg
// DO NOT EDIT!


#ifndef SESIONESPLANNING_MESSAGE_APUNTOREQUEST_H
#define SESIONESPLANNING_MESSAGE_APUNTOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sesionesPlanning
{
template <class ContainerAllocator>
struct apuntoRequest_
{
  typedef apuntoRequest_<ContainerAllocator> Type;

  apuntoRequest_()
    : direccion(0)  {
    }
  apuntoRequest_(const ContainerAllocator& _alloc)
    : direccion(0)  {
  (void)_alloc;
    }



   typedef uint8_t _direccion_type;
  _direccion_type direccion;





  typedef boost::shared_ptr< ::sesionesPlanning::apuntoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sesionesPlanning::apuntoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct apuntoRequest_

typedef ::sesionesPlanning::apuntoRequest_<std::allocator<void> > apuntoRequest;

typedef boost::shared_ptr< ::sesionesPlanning::apuntoRequest > apuntoRequestPtr;
typedef boost::shared_ptr< ::sesionesPlanning::apuntoRequest const> apuntoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sesionesPlanning::apuntoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sesionesPlanning::apuntoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sesionesPlanning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sesionesPlanning::apuntoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sesionesPlanning::apuntoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sesionesPlanning::apuntoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sesionesPlanning::apuntoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sesionesPlanning::apuntoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sesionesPlanning::apuntoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sesionesPlanning::apuntoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5bf7493d22156dd1f31812556249ef8";
  }

  static const char* value(const ::sesionesPlanning::apuntoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5bf7493d22156ddULL;
  static const uint64_t static_value2 = 0x1f31812556249ef8ULL;
};

template<class ContainerAllocator>
struct DataType< ::sesionesPlanning::apuntoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sesionesPlanning/apuntoRequest";
  }

  static const char* value(const ::sesionesPlanning::apuntoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sesionesPlanning::apuntoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 direccion\n\
";
  }

  static const char* value(const ::sesionesPlanning::apuntoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sesionesPlanning::apuntoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direccion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct apuntoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sesionesPlanning::apuntoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sesionesPlanning::apuntoRequest_<ContainerAllocator>& v)
  {
    s << indent << "direccion: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.direccion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SESIONESPLANNING_MESSAGE_APUNTOREQUEST_H
