// Generated by gencpp from file sesionesPlanning/apuntoResponse.msg
// DO NOT EDIT!


#ifndef SESIONESPLANNING_MESSAGE_APUNTORESPONSE_H
#define SESIONESPLANNING_MESSAGE_APUNTORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sesionesPlanning
{
template <class ContainerAllocator>
struct apuntoResponse_
{
  typedef apuntoResponse_<ContainerAllocator> Type;

  apuntoResponse_()
    : resultado(0)  {
    }
  apuntoResponse_(const ContainerAllocator& _alloc)
    : resultado(0)  {
  (void)_alloc;
    }



   typedef uint8_t _resultado_type;
  _resultado_type resultado;





  typedef boost::shared_ptr< ::sesionesPlanning::apuntoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sesionesPlanning::apuntoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct apuntoResponse_

typedef ::sesionesPlanning::apuntoResponse_<std::allocator<void> > apuntoResponse;

typedef boost::shared_ptr< ::sesionesPlanning::apuntoResponse > apuntoResponsePtr;
typedef boost::shared_ptr< ::sesionesPlanning::apuntoResponse const> apuntoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sesionesPlanning::apuntoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sesionesPlanning::apuntoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sesionesPlanning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sesionesPlanning::apuntoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sesionesPlanning::apuntoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sesionesPlanning::apuntoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sesionesPlanning::apuntoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sesionesPlanning::apuntoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sesionesPlanning::apuntoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sesionesPlanning::apuntoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5094b7919f0d704c7a17d30f84c3d596";
  }

  static const char* value(const ::sesionesPlanning::apuntoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5094b7919f0d704cULL;
  static const uint64_t static_value2 = 0x7a17d30f84c3d596ULL;
};

template<class ContainerAllocator>
struct DataType< ::sesionesPlanning::apuntoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sesionesPlanning/apuntoResponse";
  }

  static const char* value(const ::sesionesPlanning::apuntoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sesionesPlanning::apuntoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 resultado\n\
\n\
";
  }

  static const char* value(const ::sesionesPlanning::apuntoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sesionesPlanning::apuntoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resultado);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct apuntoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sesionesPlanning::apuntoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sesionesPlanning::apuntoResponse_<ContainerAllocator>& v)
  {
    s << indent << "resultado: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.resultado);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SESIONESPLANNING_MESSAGE_APUNTORESPONSE_H
